"""Table 1 of the benchmark paper: organisms, phases, reference conditions, gap-fill, coverage and status.

Reads only existing inputs and results (organism configs, base-model records, failure records and the
paired comparisons); no simulation. Writes docs/paper/table1_organisms.md and results/transfer_v1/table1_organisms.tsv.
"""
from __future__ import annotations

import csv
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SPECIES = {
    "Btheta": "Bacteroides thetaiotaomicron VPI-5482", "Putida": "Pseudomonas putida KT2440",
    "MR1": "Shewanella oneidensis MR-1", "Smeli": "Sinorhizobium meliloti 1021",
    "Cola": "Echinicola vietnamensis", "Dino": "Dinoroseobacter shibae", "Dyella79": "Dyella japonica",
    "MycoTube": "Mycobacterium tuberculosis H37Rv", "PS": "Dechlorosoma suillum",
    "RPal_CGA009": "Rhodopseudomonas palustris CGA009", "Caulo": "Caulobacter crescentus NA1000",
    "Cup4G11": "Cupriavidus basilensis 4G11", "Marino": "Marinobacter adhaerens HP15",
    "Miya": "Desulfovibrio vulgaris Miyazaki F", "PV4": "Shewanella loihica PV-4",
    "SB2B": "Shewanella amazonensis SB2B",
}
PHASES = [("development", "Development", "data/studies/transfer_v1/organisms.json", ["Btheta", "Putida", "MR1", "Smeli"]),
          ("evaluation_panel_A", "Panel A", "data/studies/transfer_v1/organisms_panel_A.json",
           ["Cola", "Dino", "Dyella79", "MycoTube", "PS", "RPal_CGA009"]),
          ("evaluation_panel_B", "Panel B", "data/studies/transfer_v1_replication/organisms_panel_B.json",
           ["Caulo", "Cup4G11", "Marino", "Miya", "PV4", "SB2B"])]


def main() -> None:
    rows = []
    for role, label, config, orgs in PHASES:
        cfg = json.load(open(os.path.join(ROOT, config)))["organisms"]
        paired = json.load(open(os.path.join(ROOT, "results", "transfer_v1", role, "paired.json")))
        for org in orgs:
            c = cfg.get(org, {})
            ref = c.get("reference") or {}
            base_path = os.path.join(ROOT, "models", "transfer_v1", f"{org}_base.json")
            base = json.load(open(base_path)) if os.path.exists(base_path) else None
            failure = None
            for name in (f"{org}_prepare_failure.json", f"{org}_reference_failure.json"):
                p = os.path.join(ROOT, "results", "transfer_v1", role, name)
                if os.path.exists(p):
                    failure = json.load(open(p))
            h1 = next((r for r in paired if r["org"] == org and r["A"] == "B0" and r["B"] == "UNQ" and not r.get("missing")), None)
            h2 = next((r for r in paired if r["org"] == org and r["A"] == "UNQ" and r["B"] == "M" and not r.get("missing")), None)
            if failure or not h1:
                status = "not evaluable: " + (failure["result"].split(":")[0] if failure else "no comparison")
            else:
                status = "evaluable"
            rows.append({
                "phase": label, "org": org, "species": SPECIES[org],
                "reference_medium": ref.get("medium") or (failure or {}).get("reference", {}).get("medium", "—") or "—",
                "reference_carbon": (ref.get("condition") or (base or {}).get("reference", {}).get("carbon_exchange") or "—"),
                "gapfill_reactions": len(base["added_reactions"]) if base else "—",
                "mapped_conditions": h1["n_mapped_conditions"] if h1 else "—",
                "grows_B0": h1["wt_grows_A"] if h1 else "—", "grows_U": h1["wt_grows_B"] if h1 else "—",
                "union_genes": h1["union_genes"] if h1 else "—",
                "mcc_B0": f"{h1['union_mcc_A']:.3f}" if h1 else "—",
                "mcc_U": f"{h1['union_mcc_B']:.3f}" if h1 else "—",
                "mcc_M": f"{h2['union_mcc_B']:.3f}" if h2 else "—",
                "status": status,
            })
    tsv = os.path.join(ROOT, "results", "transfer_v1", "table1_organisms.tsv")
    with open(tsv, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0]), delimiter="\t")
        w.writeheader()
        w.writerows(rows)
    lines = ["# Table 1. Organisms of the transfer study", "",
             "Generated by `scripts/make_transfer_table1.py` from existing inputs and results. Conditions: carbon-source "
             "experiments mapped to the model; grows: conditions in which the arm's model grows (B0 base, U′ automatic rules). "
             "MCC: union-gene MCC of B0 and U′ on the H1 comparison and of M on the H2 comparison (each on its own paired "
             "observations).", "",
             "| Phase | Organism | Reference condition | Gap-fill reactions | Conditions mapped | Grows B0 / U′ | Union genes | MCC B0 / U′ / M | Status |",
             "|---|---|---|---|---|---|---|---|---|"]
    for r in rows:
        lines.append(f"| {r['phase']} | {r['org']} (*{r['species']}*) | {r['reference_medium']}, {r['reference_carbon']} | "
                     f"{r['gapfill_reactions']} | {r['mapped_conditions']} | {r['grows_B0']} / {r['grows_U']} | {r['union_genes']} | "
                     f"{r['mcc_B0']} / {r['mcc_U']} / {r['mcc_M']} | {r['status']} |")
    md = os.path.join(ROOT, "docs", "paper", "table1_organisms.md")
    with open(md, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
